### PR TITLE
add sec/min/hrs/hr/days/wk/wks/weeks to time string parsing

### PR DESCRIPTION
**Pull request by ketzacoatl**
it's a first pass, feedback/guidance on the details are welcome..

This aims to address #193.

### CODE REVIEW

**Comment by ketzacoatl** [comment]
Need to address the `charLiteral` bit..

**Comment by ketzacoatl** [comment]
@NorfairKing I'm not quite sure about this.. where is `charLiteral` coming from / what would you like to replace it with if switching to a string? I went to find my own replacement, but could not figure out which library you were getting `charLiteral` from.

**Comment by ketzacoatl** [comment]
@NorfairKing, I looked a little closer, and I believe `smos-report` is using `charLiteral` from megaparsec? https://www.stackage.org/haddock/lts-17.7/megaparsec-9.0.1/Text-Megaparsec-Char-Lexer.html#g:3

That doc section notes:

> Note that you can use this parser as a building block to parse various string literals

And also:

> Performance note: the parser is not particularly efficient at the moment.

So I wonder which function you would recommend `smos-report` use here in place of `charLiteral`. Should we use `parsec`'s `stringLiteral`? https://www.stackage.org/haddock/lts-17.7/parsec-3.1.14.0/Text-Parsec-Token.html#v:stringLiteral

**Comment by NorfairKing** [comment]
@ketzacoatl `charLiteral` comes from megaparsec: https://github.com/NorfairKing/smos/blob/83b5bd3f9b39fb5560edfc5656d49bbe7e79bada/smos-report/package.yaml#L26: http://hackage.haskell.org/package/megaparsec-9.0.1/docs/Text-Megaparsec-Char-Lexer.html#v:charLiteral
I think we can use `string` instead: http://hackage.haskell.org/package/megaparsec-9.0.1/docs/Text-Megaparsec-Char.html#v:string

However, more importantly: This is a change in a parser. Parsers are notoriously hard to get right, so we'll want to start by writing tests. You can add them here: https://github.com/NorfairKing/smos/blob/83b5bd3f9b39fb5560edfc5656d49bbe7e79bada/smos-report-gen/test/Smos/Report/TimeSpec.hs#L18

**Comment by ketzacoatl** [comment]
> Parsers are notoriously hard to get right, so we'll want to start by writing tests. You can add them here

I looked that over a few times, but am having a difficult time seeing it clearly, so I'm not even sure I can explain how that existing spec is testing `timeP`. Maybe we could meet up and review this together.

**Comment by NorfairKing** [comment]
Sure we can discuss it together!

**Comment by ketzacoatl** [comment]
@NorfairKing This is now ready for your review ;)

**Comment by NorfairKing** [comment]
LGTM

**Pull request merged**
