### PR TITLE
Do not open the firewall by default

### PR DESCRIPTION
**Pull request by prescientmoon**
This mirrors the recent intray change

### CODE REVIEW

**Comment by prescientmoon** [comment]
I added an additional commit, as the module was failing when the api-server was given no hosts.

**Comment by NorfairKing** [comment]
@Mateiadrielrafael In general we need `nix flake check` to pass before merging anything, and a changelog entry.
Unfortunately I think that might involve more ceremony than we'd like, because we'd need a forward-compatible release in order for that to work.
I'm open to turning off `e2e-test-forward-compatibility` for this release.

What do you think?

**Comment by prescientmoon** [comment]
@NorfairKing Would forward compatibility be restored by simply making the openFirewall option on by default?

**Comment by NorfairKing** [comment]
@Mateiadrielrafael Yes, that's an option. Then we need another commit for the next release to set that default to `false`.

**Comment by prescientmoon** [comment]
@NorfairKing Sure, that's fine.

**Comment by NorfairKing** [comment]
@Mateiadrielrafael I'll push a commit in a moment. One moment.

**Comment by NorfairKing** [comment]
@Mateiadrielrafael Please see the `firewall` branch.

**Comment by prescientmoon** [comment]
> @Mateiadrielrafael Please see the `firewall` branch.

Yep, that looks good!

**Comment by NorfairKing** [comment]
I just released a new version with this change, and the next release will have the default be `false`.

**Pull request closed without merging**
