### PR TITLE
Automatic niv-update - 2021-05-12

### PR DESCRIPTION
**Pull request by NorfairKing**

### CODE REVIEW

**Comment by ketzacoatl** [comment]
@NorfairKing, I'm curious about this, could you explain or point me to resources where I might better understand what is going on here?

**Comment by NorfairKing** [comment]
This is me trying out some automation (and failing). Please ignore it :p

**Comment by ketzacoatl** [comment]
For what I could ascertain, it seemed fascinating and something I'd be interested in. I'll ignore for now :)

**Comment by ketzacoatl** [comment]
For what I could ascertain, it seemed fascinating and something I'd be interested in. I'll ignore for now :)

**Pull request merged**
