### PR TITLE
refactor the next report to re-use the entry code

### LINKED ISSUE #86: Refactor the `next` report to use the entry report internally
There is quite a bit of code duplication here for no reason. The next action report is just an entry report with a specific filter.

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Fixes #86

### CODE REVIEW

**Comment by NorfairKing** [comment]
Wow I am so impressed that someone picked this up. Thanks!

**Comment by NorfairKing** [comment]
I like these refactors but it's not what I meant in #86.
What I'm talking about is that the next action report can be expressed as an entry report with a fixed filter: https://github.com/NorfairKing/smos/pull/87/files#diff-dd4cd64187dbbd39c0b1fb764c547118R48

The filter will be an `EntryFilterRel` that represents "The state is NEXT or STARTED".

I can merge this PR as-is and leave 86 open, or you can add that to this PR. Up to you.

**Comment by TristanCacqueray** [comment]
You're welcome, thank you for the direction. I think I understood, let me give this a try.

**Comment by TristanCacqueray** [comment]
I'm actually not sure what you meant. I was able to replace the NextActionReport by the EntryReport using the `isNextFilter :: EntryFilterRel` but that makes the Commands.Next formatter fail. So I guess you meant that the new `produceReport` function needs to also take the `makeNextActionReport` function as a parameter, but I don't understand how to make it compatible with the existing `makeEntryReport`. To do that, I've been reading about the cursor library, alas I am not able to figure out a `CursorForest a -> a` function.

Alternatively, perhaps it is possible to simply adapt the EntryReport at the end, e.g. using a `Projectee -> NextActionEntry` function. It would be great if you could provide a bit more details, otherwise, while this is very instructive, I'm afraid the code is too far above my current understanding of the language :-)

**Comment by NorfairKing** [comment]
Ok. I want to help you but I don't want to take away a learning opportunity from you so I'll give you the choice: I can try to explain it extra-well, or I can do it and show you. Which would you prefer?

**Comment by TristanCacqueray** [comment]
Thank you for your consideration. I think it would be easier if you could do and show what you have in mind.

**Comment by NorfairKing** [comment]
@TristanCacqueray I'm a complete dummy. The changes I was looking for have already been implemented before. I'm merging this as-is. Thank you for your contribution! Please let me know if you'd like to contribute some more and would like some help or if you'd like me to help with some set up. 

Here is  the link to the code I meant: https://github.com/NorfairKing/smos/pull/87/files#diff-dd4cd64187dbbd39c0b1fb764c547118R37-R43

**Pull request merged**
