### PR TITLE
add custom exitNextActionReport Action (WIP)

### LINKED ISSUE #169: q not working with "Next action report"
When the user uses "rn" and goes to the "Next action report", the user can't quit smos with "q". The user has to select a task or use browse actions to be able to quit smos.

### PR DESCRIPTION
**Pull request by ketzacoatl**
This isn't fully correct, but getting closer. This is to resolve #169.

### CODE REVIEW

**Comment by NorfairKing** [comment]
I think you bound the key in a place that would work, but `reportsKeymapAnyMatchers` would be better I think. What you're writing applies to exiting any report, I think.
I think what you're missing at the moment is that the action you defined doesn't _do_ anything.
You can look at `Smos.Actions.Utils` for helper functions for fixing that.

**Comment by ketzacoatl** [comment]
Thanks for the review.

I eventually found `quit` and followed the action there.

If I understand correctly, the existing `quit` Action already handles the "quit when we have an existing file open", so the "quit Next Action Report when there's no file" is handled by the new action I've added.

In my testing, this seems to work. However, I'm not sure about the following two items:
* The existing `quit` action is defined in `Smos.Types` rather than `Smos.Actions`, but that might be due to some circular dependency (and I haven't made an attempt to move it). Does it belong there where it's at, or should it be moved to `Smos.Actions`? If you would like to move it, I will do that in a separate PR.
* With the new Action I've added, we now have two Actions for "quit", and maybe that's fine, but I wonder if this would be confusing in the future? Should the two be combined, or maybe the new function as an alias for `quit`, some other change, or is this preferred as-is?

If my existing update works for you, I'd prefer to merge and make new PRs for additional changes, but LMK if you see changes you would like me to make before merging.

**Comment by ketzacoatl** [comment]
Another update to get the build green.

**Comment by NorfairKing** [comment]
First of all: thanks for taking this on, it's nice to have some more smos contributors!

>  ketzacoatl force-pushed the ketzacoatl:wip-exit-next-action-report branch from 7041902 to 8989d29 yesterday

Please don't force-push unless it's because you rebased. We can always squash later and force-pushing means I need to re-review everything instead of just the latest changes.
 
>    The existing quit action is defined in Smos.Types rather than Smos.Actions, but that might be due to some circular dependency (and I haven't made an attempt to move it). Does it belong there where it's at, or should it be moved to Smos.Actions? If you would like to move it, I will do that in a separate PR.

That's because of circular dependencies, you can just leave it there, but thanks for checking!

> With the new Action I've added, we now have two Actions for "quit", and maybe that's fine, but I wonder if this would be confusing in the future? Should the two be combined, or maybe the new function as an alias for quit, some other change, or is this preferred as-is?

I think the way you've defined it here, it will just exit smos entirely, instead of doing this:

```
-- Exit the Next Action Report
-- If there is a file open, go to it (this already works?)
-- If there is no file open, go to the browser in the workflow dir
```

Also, this action can be used to exit any report, not just the next action report, so let's call it `exitReport` instead.

Also the tests fail, make sure to run `stack test smos` because there are some tests to make sure that docs are up to date :D

**Comment by ketzacoatl** [comment]
@NorfairKing,

> First of all: thanks for taking this on, it's nice to have some more smos contributors!

:rocket: 

> Please don't force-push unless it's because you rebased. We can always squash later and force-pushing means I need to re-review everything instead of just the latest changes.

OK.

> That's because of circular dependencies, you can just leave it there, but thanks for checking!

Yea, I had the feeling. That makes sense.

> I think the way you've defined it here, it will just exit smos entirely, instead of doing this:

-- Exit the Next Action Report
-- If there is a file open, go to it (this already works?)
-- If there is no file open, go to the browser in the workflow dir

Ah yes, silly me.

Two questions on that: is there an existing function to tell me about the file that is open? I see `switchToFile` but don't know how to get `fp` for that. And then would `actionFunc selectBrowserWorkflow` "go to the browser in the workflow dir"?

> Also, this action can be used to exit any report, not just the next action report, so let's call it exitReport instead.

OK, I have renamed to `exitReport` and moved the function to a `Actions.Report.Exit` module.

> Also the tests fail, make sure to run stack test smos because there are some tests to make sure that docs are up to date :D

Ah, yes, thanks for the reminder, I will sort that out.

**Comment by ketzacoatl** [comment]
@NorfairKing, I'm not sure how to make the new `exitReport` available to `nextActionReportAnyMatchers`, but maybe that isn't the right thing todo now?

image

**Comment by NorfairKing** [comment]
@ketzacoatl You're missing an import and/or export somewhere. Probably at the top of `Smos.Actions`. 
To be fair, I think you could have just put the action in `Smos.Actions.Report`.

**Comment by ketzacoatl** [comment]
@NorfairKing,

> To be fair, I think you could have just put the action in `Smos.Actions.Report`.

If I move `exitReport` to `Smos.Actions.Report`, should it get hooked up into `allPlainReportActions` and `allReportUsingActions` directly?

EDIT: Adding it in directly doesn't work, but I did something that compiles, LMK if it should be different.

**Comment by NorfairKing** [comment]
> If I move exitReport to Smos.Actions.Report, should it get hooked up into allPlainReportActions and allReportUsingActions directly?

Yes that's right I think.

**Comment by ketzacoatl** [comment]
> > If I move exitReport to Smos.Actions.Report, should it get hooked up into allPlainReportActions and allReportUsingActions directly?
> 
> Yes that's right I think.

I had to meet in the middle, but it compiles and I think it's right (seems to function correctly in my testing).

There is a build failure from `ormolu` I haven't been able to decipher: 
image

Wasn't there also a doc update I needed to make for this, where is that, or how can I find out more about what that should be?

Lastly, is there a test I could write for this feature so we know it works?

**Comment by NorfairKing** [comment]
> There is a build failure from ormolu I haven't been able to decipher:

You need to run the pre-commit hooks before committing, otherwise CI will fail saying that you didn't.
Run `nix-shell` then `pre-commit run -a` to fix this.

> Wasn't there also a doc update I needed to make for this, where is that, or how can I find out more about what that should be?

I don't think so, the docs for this are generated.

> Lastly, is there a test I could write for this feature so we know it works?

Yes, a scenario test, see `smos/test/Smos/ScenarioSpec.hs` and the scenarios in `smos/test_resources`.

**Comment by ketzacoatl** [comment]
> Yes, a scenario test, see smos/test/Smos/ScenarioSpec.hs and the scenarios in smos/test_resources.

@NorfairKing, ok, so I see the specs in `smos/test_resources`, and the report scenario too, though I am not sure: What should be tested here? Do we have two/multiple scenarios? Eg Open the next action report with no open smos file, then quit, and then separately, open the next action report and quit when there's an open smos file? How do I confirm successful result with the quit?

**Comment by NorfairKing** [comment]
@ketzacoatl 

> ok, so I see the specs in smos/test_resources, and the report scenario too, though I am not sure: What should be tested here? > Do we have two/multiple scenarios? Eg Open the next action report with no open smos file, then quit, and then separately, open > the next action report and quit when there's an open smos file? How do I confirm successful result with the quit?

We need to come up with a test that fails before your changes and succeeds afterwards. (You can use CI to verify that the regression test indeed fails.)
I like the idea of the two scenarios.
You can only assert the contents of the workflow dir before, so the test will have to change something in a file and assert that the change has been made. Does that make sense?

**Comment by NorfairKing** [comment]
@ketzacoatl I'm merging this in manually right now. Thanks a lot for the effort, I'll mention you in the changelog shortly as `ketzacoatl`. If you'd like to be named under a different identifier (or not at all), please let me know!

**Comment by NorfairKing** [comment]
This is now on `development`! :D Thank you @ketzacoatl

**Pull request closed without merging**
